### ISSUE TITLE
WSS not connected 

### ISSUE THREAD

**Issue by josefrasetia** [RodrigoBertotti/flutter_chat_app_with_nodejs#4]
my web socket secure not connected in askless, but connect in another app, what is wrong?
<img width="233" alt="Screenshot 2024-01-07 181618" src="https://github.com/RodrigoBertotti/flutter_chat_app_with_nodejs/assets/36933081/645160aa-9daa-4237-be99-dbd64d08d6ff">

![WhatsApp Image 2024-01-07 at 18 29 59_486381d4](https://github.com/RodrigoBertotti/flutter_chat_app_with_nodejs/assets/36933081/7679df7e-57ff-41ba-b278-110eb47beb84)

**Comment by RodrigoBertotti** [comment]
I'm not sure, please check if your App is using the correct URL starting with `wss://` and if the URL you mentioned is actually hosting the Askless backend server (not another server)

Please try to solve your problem searching about WebSocket encryption, I will close the issue because it doesn't look like an Askless issue
